=== drarekx/PAFM04/persona_xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="personas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="persona" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="persona">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="apellido" type="xs:string"/>
                <xs:element name="edad" type="xs:integer"/>
                <xs:element name="email" type="xs:string"/>
                <xs:element ref="germans" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="aficions" type="xs:string" use="optional"/>
            <xs:attribute name="edat" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="germans">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="persona" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== drarekx/PAFM04/persona_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="persona_xsd.xsd">
    <persona aficions="programacio" edat="39">
        <nombre>Gerard</nombre>
        <apellido>Fortea</apellido>
        <edad>36</edad>
        <email>gerard.fortea@example.com</email>
        <germans>
            <persona aficions="pastissos" edat="44">
                <nombre>Gemma</nombre>
                <apellido>Fortea</apellido>
                <edad>44</edad>
                <email>gemma.fortea@gmail.com</email>
            </persona>
        </germans>
    </persona>
    <persona aficions="circ" edat="36">
        <nombre>Eva</nombre>
        <apellido>Mart√≠nez</apellido>
        <edad>32</edad>
        <email>eva.martinez@example.com</email>
        <germans>
            <persona aficions="claque" edat="35">
                <nombre>Pau</nombre>
                <apellido>Camps</apellido>
                <edad>35</edad>
                <email>pau.camps@gmail.com</email>
            </persona>
        </germans>
    </persona>
</personas>
